# Generated by Django 5.2.14 on 2026-05-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonitoringResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        max_length=10,
                    ),
                ),
                ("ping_ms", models.FloatField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-checked_at"],
            },
        ),
    ]
