# Generated by Django 5.2.14 on 2026-05-23 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0002_monitoringstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitorTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("url", models.URLField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "check_interval",
                    models.PositiveIntegerField(
                        default=30, help_text="Sekundlarda monitoring intervali."
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="monitoringresult",
            name="response_status_code",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monitoringresult",
            name="response_time_ms",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monitoringresult",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="monitoring.monitortarget",
            ),
        ),
        migrations.AddField(
            model_name="monitoringstate",
            name="target",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitoring_state",
                to="monitoring.monitortarget",
            ),
        ),
    ]
