# Generated by Django 5.2.14 on 2026-05-23 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "monitoring",
            "0003_monitortarget_monitoringresult_response_status_code_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("email", "Email")],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Warning"), ("critical", "Critical")],
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddField(
            model_name="monitoringstate",
            name="consecutive_failures",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monitoringstate",
            name="last_notification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monitoringstate",
            name="last_notification_severity",
            field=models.CharField(
                blank=True,
                choices=[("warning", "Warning"), ("critical", "Critical")],
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringresult",
            index=models.Index(
                fields=["target", "-checked_at"], name="monitoring__target__db091a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringresult",
            index=models.Index(
                fields=["status", "-checked_at"], name="monitoring__status_11c719_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringresult",
            index=models.Index(
                fields=["response_status_code"], name="monitoring__respons_bee681_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitortarget",
            index=models.Index(
                fields=["is_active", "last_status"],
                name="monitoring__is_acti_b2ad3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitortarget",
            index=models.Index(
                fields=["updated_at"], name="monitoring__updated_b6edd3_idx"
            ),
        ),
        migrations.AddField(
            model_name="notificationhistory",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="monitoring.monitortarget",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationhistory",
            index=models.Index(
                fields=["target", "-sent_at"], name="monitoring__target__0f2053_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationhistory",
            index=models.Index(
                fields=["channel", "severity"], name="monitoring__channel_0bd0ce_idx"
            ),
        ),
    ]
